### ISSUE TITLE
tried building with ./gradlew build but it failed

### ISSUE THREAD

**Issue by Unknown-User2** [Gavhack-development/Gavhack#7]
i tried build the mod on arch linux fully up to date with ./gradlew build and it failed all the command [output](https://pastebin.com/tvYNyN7p)

**Comment by Gav06** [comment]
make sure you have the right java version installed

**Comment by Unknown-User2** [comment]
what is the right version

**Comment by Gav06** [comment]
8

**Comment by Unknown-User2** [comment]
i have that installed

**Comment by Gav06** [comment]
idk

**Comment by Unknown-User2** [comment]
i added the line `org.gradle.java.home=/usr/lib/jvm/java-8-openjdk` and it built but when i run it doesnt run and give exit code 0

**Comment by Gav06** [comment]
well im not entirely sure why, the crash report is kind of vague, but i know that this is an issue only for you, seeing as it still builds for github ci

**Comment by Unknown-User2** [comment]
it doesnt give me a crash report it just says "ERROR Game crashed An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit Code: 0"

**Comment by Gav06** [comment]
check latest.log

**Comment by Gav06** [comment]
oh lord

**Comment by Gav06** [comment]
i have gotten that error and have no clue how to fix

**Comment by Unknown-User2** [comment]
lol

**Comment by Gav06** [comment]
:/

**Comment by Gav06** [comment]
maybe i need to fix how my mixins are setup

**Comment by AcaiBerii** [comment]
Maybe a commit that I accidentally made or your operating system. It seems to run and build fine for me.

**Comment by Unknown-User2** [comment]
its not my os because gavin said it happened to him 

im not running it with any other mods

i reinstalled groovy and it still happens

**Comment by gerald0mc** [comment]
> its not my os because gavin said it happened to him
> 
> im not running it with any other mods
> 
> i reinstalled groovy and it still happens

user error stay mad :trollface:

**Comment by Unknown-User2** [comment]
if anything its your fault bc i just downloaded it and tried to build it

**Comment by AcaiBerii** [comment]
> > its not my os because gavin said it happened to him
> > im not running it with any other mods
> > i reinstalled groovy and it still happens
> 
> user error stay mad :trollface:

:trollface:

**Comment by mmmaxcode** [comment]
Tfw build failure because not using the superior os (fortniteDistro) cope

**Comment by Gav06** [comment]
!!!!!!!
